### ISSUE TITLE
Parcel build breaks, keyboardjs and rebound missing

### ISSUE THREAD

**Issue by WesSouza** [streamich/react-use#183]
I see #167 moved `keyboardjs` and `rebound` to `devDependencies`, but this seems to be causing issues, at least with Parcel which is what I use on my project.

```
$ npx parcel build ./src/index.html --public-url '/'
🚨  /Users/wesley/Sites/subway-time/node_modules/react-use/esm/useKeyPress.js:12:15: Cannot resolve dependency 'keyboardjs'
  10 |     var useKeyboardJS = config.useKeyboardJS;
  11 |     if (useKeyboardJS) {
> 12 |         import("keyboardjs").then(setKeyboardJs);
     |               ^
  13 |     }
  14 |     var regularDownHandler = function (_a) {
  15 |         var key = _a.key;
```

**Comment by streamich** [comment]
It was moved out of dependencies as requested here: https://github.com/streamich/react-use/issues/102

And proposed in this PR: https://github.com/streamich/react-use/pull/161

**Comment by kurohune538** [comment]
I met same error with webpack build in spite of using `useSpring`.
Do we have to do `yarn add rebound keyboardjs` anyway?

**Comment by streamich** [comment]
I am using this library by directly importing only the needed hooks, like

```js
import useClickAway from 'react-use/lib/useClickAway';
```

There is also a convenience way

```js
import {useClickAway} from 'react-use';
```

Maybe we should remove the second option, or at least recommend the first option in docs.

1. Then we will not have people complaining about big bundle size.
2. Will not have builds failing because some dependencies are missing and have to be installed separately.
3. There were also TypeScript issues when importing using the second option, because some dependencies did not have proper TypeScript typings.

**Comment by jimmyleray** [comment]
I have similar error on tests suites since react-use version 6/7 :

Cannot find module 'rebound' from 'useSpring.js'

**Comment by wardoost** [comment]
@jimmyleray For now you can either import hooks like
```js
import useClickAway from 'react-use/lib/useClickAway';
```
or transform
```js
import useClickAway from 'react-use';
```
to the first import statement with a plugin as described in https://github.com/streamich/react-use/issues/102#issuecomment-475909523
