### ISSUE TITLE
useEventListener

### ISSUE THREAD

**Issue by himStone** [streamich/react-use#400]
https://github.com/streamich/react-use/search?q=addEventListener&unscoped_q=addEventListener

I found we use many `addEventListener`、`removeEventListener` in this repo, shall we  consider moving that logic to a custom hook which named `useEventListener` or `useDocumentEvent`

```
const useMouseMove = () => {
  const [coords, setCoords] = useState([0, 0]);

  useEventListener('mousemove', ({ clientX, clientY }) => {
    setCoords([clientX, clientY]);
  });

  return coords;
};
```

see: https://github.com/donavon/use-event-listener

**Comment by streamich** [comment]
There is [`useEvent`](https://github.com/streamich/react-use/blob/master/docs/useEvent.md) hook for that, but I would not go and modify all places to use that, because you need to memoize listener you give to `useEvent`.

```js
useEvent('mousemove', useCallback(onMouseMove))
```

Whereas if you do subscription using `.addEventListener` inside `useEffect` you don't need to do that.

**Comment by himStone** [comment]
Thanks for the reply.
