### ISSUE TITLE
warning in console when using useSize

### ISSUE THREAD

**Issue by piehouserat** [streamich/react-use#584]
When using the useSize hook my component being sized gets the correct dimensions, however, I get the following warning in the console:

```Warning: `Infinity` is an invalid value for the `width` css style property.```

I imagine this is due to the useSize hook having default dimensions of 'Infinity' for both width and height. Is there any way to redefine these values as probably simply setting them to 0 for their initial state should solve this

**Comment by wardoost** [comment]
`Infinity` is the default value for both width and height indeed. I think this is because this library is based on work @streamich did on libreact: https://github.com/streamich/libreact/blob/master/src/SizeSensor/index.ts#L21

Using `0` as a default value makes sense but I think we have to be mindful that you might do a division with this value. This will result in a value `Inifinity` again so maybe this is why `Infinity` was chosen as a default value in the first place?

Let's see what other users/contributors think.

**Comment by streamich** [comment]
The reason is because it uses `<iframe>` to calculate element dimensions and needs to render once first before it knows the dimensions. The defaults are chosen as `Infinity` so that it is still a number and clear that dimensions have not been calculated yet. It could also be `-1` or `0`, but I used `Infinity` 🤷‍♂️

You might also want to take a look at [`useMeasure`](https://github.com/streamich/react-use/blob/master/docs/useMeasure.md).

**Comment by wardoost** [comment]
`useMeasure` seems to initialise with 0 values. It's generally also considered best practice to render mobile-first. Changing the default value to 0 would make more sense because of these things.

@piehouserat You can set the initial values with [the second argument](https://github.com/streamich/react-use/blob/master/src/useSize.tsx#L17), this should probably be added to the docs.

**Comment by piehouserat** [comment]
thanks for the help guys, problem solved :)

also, many thanks for creating such a useful collection of hooks, I can see this library saving me a lot of time in the future!
