### ISSUE TITLE
how to add parameter to useAsync

### ISSUE THREAD

**Issue by lanceMe** [streamich/react-use#628]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lanceMe** [comment]
i want add parameters to callback，but not suport!

**Comment by edkimmel** [comment]
I believe you should switch to useAsyncFn instead.  The only thing useAsync seems to do extra is call the function automatically.

**Comment by xobotyi** [comment]
As useEffect callback has no parameters this one has none too.

**Comment by wardoost** [comment]
@lanceMe An example on how to use `useAsync` with a promise that depends on an `url` parameter:

```js
function MyComponent({url}) {
  const state = useAsyncFn(() => fetch(url).text(), [url])

  return ...
}
```

The second parameter of the hook is the dependency list. In this example it contains `url` which means whenever the url changes the promise will execute again. This is a similar mechanic of how standard React hooks like `useEffect` work as per @xobotyi comment.

Currently the types don't seem to be correct so that will need to be fixed. There are currently a few PR's open regarding type issues with async hooks so I'll need to have a look if one of those actually fixes this issue.

@edkimmel `useAsyncFn` would be used when you want to track async state of a callback, an example:

```js
function MyComponent({url}) {
  const [state, callback] = useAsyncFn(() => fetch(url).text(), [url])

  return (
    <>
      <button onClick={callback}>Load data</button>
      ...
    </>
  )
}
```

Renaming to or having an alias `useAsyncCallback` could make this more clear, what do you think?
