### ISSUE TITLE
useMap(): outdated closure in `utils.get` method

### ISSUE THREAD

**Issue by stefanbugge** [streamich/react-use#816]
**What is the current behavior?**

The value returned by the `get` is incorrect

https://github.com/streamich/react-use/blob/master/src/useMap.ts#L15
```
const utils = useMemo<Actions<T>>(
  () => ({
    // The reference to `map` is outdated
    get: key => map[key],
    // ...
  }),
  [set] // `map` is missing here in the dependency array.
);
```

**Comment by giladaya** [comment]
This change caused the value of `set` to change on each render which may break expected behaviour.  
Specifically, I would expect the value of the set function to be stable between renders, same as it is in `useState` hook.  
When it's not stable it may cause initialisations done in a `useEffect` calls to cause an infinite render loop.  
  
For example, this component used to work properly:
```javascript
const INITIAL_COUNT_VALUE = 5;

function DemoUseMap() {
  const [map, { set }] = useMap({});
  React.useEffect(() => {
    set('count', INITIAL_COUNT_VALUE);
    console.log('Run effect');
  }, [set]);
  return <div>Foo {map.count}</div>;
}
```

**Comment by stefanbugge** [comment]
Good point.
Would it suffice to have to have the individual methods with side-effects stable across renders, i.e. `set`, `reset`, `remove` but not the actual `utils` object?

**Comment by giladaya** [comment]
I think it makes sense
