### ISSUE TITLE
usePrevious returns undefined

### ISSUE THREAD

**Issue by ThinkSalat** [streamich/react-use#991]
Hi,

I'm on the latest version of react-use. usePrevious is returning undefined. I have tried arrays, objects, primitives, etc, and they all return undefined.

**Comment by xobotyi** [comment]
The first return of that hook is always `undefined`, because you dont have a previous value for first render.
Provide a code example (issue template made not because we have nothig to do)

**Comment by ThinkSalat** [comment]
Oh you know what, I think my component was re-mounting or something which was resetting the usePrevious state back to undefined every time.

**Comment by einarq** [comment]
Not sure if I should open a new issue or raise the question here, but it seems very relevant to this thread so raising it here for now.

I understand that the previous value to the initial render will always be undefined, and that the hook is therefore doing the "correct" thing. 
For me the main use case for usePrevious is to check if a value changes. and if it changes you might want to do something (there are of course a lot of other use cases I'm sure). 
For me the current behavior means I cannot do this without also adding some extra checks.

I have a flag for validation called "isValid", and if that flag changes I want to take some action.
Using the usePrevious hook, I cannot simply do this, since this will always be true on the initial render:
if(isValid !== prevIsValid) {
  // do something
}

I have to do this instead:
if(prevIsValid !== undefined && isValid !== prevIsValid) {
  // do something
}

Seems to me this could lead to some subtle bugs as well.

I might be thinking about it all wrong, just not able to see how atm :)

**Comment by xobotyi** [comment]
@einarq Main purpose of `usePrevious` is to store given value of any variable between adjacent calls.

The way you doing it now looks absolutely fine to me, only issue it can lead will occur when your original `isValid` become `undefined`.

I barely can imagine other common logic for this hook. Even giving possibility to define initial value sounds incorrect for me.
